name: Capstone Project CI/CD

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  # === CI Jobs ===
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install backend dependencies
        working-directory: ./
        run: npm ci

      - name: Run backend linter
        working-directory: ./backend
        run: npm run lint

      - name: Run backend tests
        working-directory: ./
        run: npm test

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend linter
        working-directory: ./frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test

  # === CD Jobs ===
  deploy-staging:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/staging'

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Vercel (Staging)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--confirm"

  deploy-production:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"


# === Rollback Jobs ===
  rollback-staging:
    needs: deploy-staging
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Rollback to last successful staging deployment
        run: |
          echo "Rolling back to the last successful staging build..."
          vercel rollback ${{ secrets.VERCEL_PROJECT_ID }} --token ${{ secrets.VERCEL_TOKEN }}
      - name: Notify rollback
        run: echo "Rollback to the last staging deployment completed."

  rollback-production:
    needs: deploy-production
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Rollback to last successful production deployment
        run: |
          echo "Rolling back to the last successful production build..."
          vercel rollback ${{ secrets.VERCEL_PROJECT_ID }} --prod --token ${{ secrets.VERCEL_TOKEN }}
      - name: Notify rollback
        run: echo "Rollback to the last production deployment completed."
